# Weather Flower App Configuration

# Default configuration
server:
  debug: true
  host: "127.0.0.1"
  port: 5000
  threaded: true

app:
  defaultClimate: "cool"
  defaultSeason: "spring"
  # Generate a new secret key for production: python -c "import secrets; print(secrets.token_hex(32))"
  secretKey: "dev-key-not-for-production-use"

logging:
  level: "INFO"

# Environment-specific overrides
development:
  server:
    debug: true
    port: 5000
  logging:
    level: "DEBUG"

production:
  server:
    debug: false
    host: "0.0.0.0"
    port: 5000
    threaded: true
  # Secret key should be set via FLASK_SECRET_KEY environment variable in production
  logging:
    level: "WARNING"

testing:
  server:
    debug: true
    port: 9000
  logging:
    level: "DEBUG"
