name: Deploy to Azure Container Apps

on:
  push:
    branches: 
      - main
      - master
  workflow_dispatch:

env:
  ACR_NAME: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_NAME: weatherflower

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Verify branch
      run: |
        echo "Triggered by branch: ${{ github.ref_name }}"
        echo "Event name: ${{ github.event_name }}"
        if [[ "${{ github.ref_name }}" != "main" && "${{ github.ref_name }}" != "master" ]]; then
          echo "❌ This workflow should only run on main/master branches"
          echo "Current branch: ${{ github.ref_name }}"
          exit 1
        fi
        echo "✅ Branch check passed: ${{ github.ref_name }}"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.ACR_NAME }}

    - name: Build and push Docker image
      run: |
        # Build the image
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest .
        
        # Push the image
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    - name: Create short revision suffix
      id: revision
      run: |
        # Create a short revision suffix (first 8 chars of SHA + timestamp)
        SHORT_SHA="${{ github.sha }}"
        SHORT_SHA="${SHORT_SHA:0:8}"
        TIMESTAMP=$(date +%m%d%H%M)
        REVISION_SUFFIX="rev-${SHORT_SHA}-${TIMESTAMP}"
        echo "suffix=${REVISION_SUFFIX}" >> $GITHUB_OUTPUT
        echo "Created revision suffix: ${REVISION_SUFFIX}"

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --revision-suffix ${{ steps.revision.outputs.suffix }} \
          --set-env-vars FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}
